# Generated by Django 2.0.2 on 2019-08-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_restaurant_id', models.CharField(max_length=200, null=True)),
                ('item_id', models.CharField(max_length=10, null=True)),
                ('item_name', models.CharField(max_length=20, null=True)),
                ('item_detail', models.CharField(max_length=200, null=True)),
                ('item_price', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
