# Generated by Django 2.0.2 on 2019-08-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_description',
            name='restaurant_Address',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurant_description',
            name='restaurant_Details',
            field=models.CharField(default='SOME STRING', max_length=2000),
        ),
        migrations.AddField(
            model_name='restaurant_description',
            name='restaurant_email',
            field=models.EmailField(default='SOME STRING', max_length=150),
        ),
        migrations.AddField(
            model_name='restaurant_description',
            name='restaurant_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant_description',
            name='restaurant_number',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant_description',
            name='restaurant_owner_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant_description',
            name='restaurant_owner_phone_number',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant_description',
            name='restaurant_photo_link',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
