# Generated by Django 2.0.2 on 2019-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_authentication', '0002_auto_20190811_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_description',
            name='restaurant_Address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_description',
            name='restaurant_Details',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_description',
            name='restaurant_email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_description',
            name='restaurant_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_description',
            name='restaurant_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_description',
            name='restaurant_owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_description',
            name='restaurant_owner_phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_description',
            name='restaurant_photo_link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
