# Generated by Django 2.0.2 on 2019-08-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_package_name', models.CharField(max_length=250, null=True)),
                ('restaurant_package_price', models.IntegerField(max_length=50, null=True)),
                ('restaurant_package_specification', models.CharField(max_length=2000, null=True)),
                ('restaurant_package_validity', models.DateTimeField(null=True)),
                ('restaurant_package_id', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
