# Generated by Django 2.0.2 on 2019-08-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_package',
            name='restaurant_package_id',
            field=models.IntegerField(null=True),
        ),
    ]
