# Generated by Django 2.0.2 on 2019-08-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_package', '0002_auto_20190814_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_package',
            name='restaurant_package_price',
            field=models.IntegerField(null=True),
        ),
    ]
