# Generated by Django 2.0.2 on 2019-08-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_id', models.CharField(max_length=200, null=True)),
                ('service_id', models.CharField(max_length=200, null=True)),
                ('user_id', models.CharField(max_length=200, null=True)),
                ('starting', models.CharField(max_length=20, null=True)),
                ('ending', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
